2021-08-05 11:50:13,962 WARNING: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:50:23,973 WARNING: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:50:33,988 WARNING: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:50:43,993 WARNING: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:50:54,003 WARNING: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:04,028 WARNING: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:14,038 WARNING: Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:24,043 WARNING: Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:34,063 WARNING: Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:44,073 WARNING: Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:51:54,083 WARNING: Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:04,113 WARNING: Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:14,138 WARNING: Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:24,148 WARNING: Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:34,170 WARNING: Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:44,208 WARNING: Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:52:54,243 WARNING: Shard ID None heartbeat blocked for more than 170 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:04,253 WARNING: Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:14,262 WARNING: Shard ID None heartbeat blocked for more than 190 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:24,277 WARNING: Shard ID None heartbeat blocked for more than 200 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:34,283 WARNING: Shard ID None heartbeat blocked for more than 210 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:44,293 WARNING: Shard ID None heartbeat blocked for more than 220 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:53:54,313 WARNING: Shard ID None heartbeat blocked for more than 230 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:04,322 WARNING: Shard ID None heartbeat blocked for more than 240 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:14,332 WARNING: Shard ID None heartbeat blocked for more than 250 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:24,388 WARNING: Shard ID None heartbeat blocked for more than 260 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:34,407 WARNING: Shard ID None heartbeat blocked for more than 270 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:44,422 WARNING: Shard ID None heartbeat blocked for more than 280 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:54:54,452 WARNING: Shard ID None heartbeat blocked for more than 290 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 78, in create_missing_member_fluctlight
    member_vice_fluct = vice_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:04,462 WARNING: Shard ID None heartbeat blocked for more than 300 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 77, in create_missing_member_fluctlight
    member_main_fluct = main_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:14,462 WARNING: Shard ID None heartbeat blocked for more than 310 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\sqcs_plugin\fluctlight.py", line 97, in delete_unused_fluctlight
    for member_data in main_data:
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1175, in _refresh
    self.__send_message(g)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 215, in receive_message
    data = _receive_data_on_socket(sock_info, length - 16, deadline)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:24,477 WARNING: Shard ID None heartbeat blocked for more than 320 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:34,482 WARNING: Shard ID None heartbeat blocked for more than 330 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:44,492 WARNING: Shard ID None heartbeat blocked for more than 340 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:55:54,502 WARNING: Shard ID None heartbeat blocked for more than 350 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:04,512 WARNING: Shard ID None heartbeat blocked for more than 360 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:14,512 WARNING: Shard ID None heartbeat blocked for more than 370 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:24,522 WARNING: Shard ID None heartbeat blocked for more than 380 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:34,532 WARNING: Shard ID None heartbeat blocked for more than 390 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:44,546 WARNING: Shard ID None heartbeat blocked for more than 400 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:56:54,566 WARNING: Shard ID None heartbeat blocked for more than 410 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:57:04,577 WARNING: Shard ID None heartbeat blocked for more than 420 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:57:14,587 WARNING: Shard ID None heartbeat blocked for more than 430 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:57:24,602 WARNING: Shard ID None heartbeat blocked for more than 440 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

2021-08-05 11:57:34,602 WARNING: Shard ID None heartbeat blocked for more than 450 seconds.
Loop thread traceback (most recent call last):
  File "d:\src\Github\phantom0174\SQCS_bot\main.py", line 26, in <module>
    bot.run()
  File "d:\src\Github\phantom0174\SQCS_bot\bot\bot.py", line 43, in run
    super().run(token, reconnect=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files (x86)\Python\Python_3.9.4\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "d:\src\Github\phantom0174\SQCS_bot\bot\cogs\task.py", line 28, in role_update_check
    member_active_data = fluctlight_cursor.find_one({"_id": member.id})
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 196, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\network.py", line 287, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 129, in recv_into
    return self._call(super(_sslConn, self).recv_into, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\pymongo\pyopenssl_context.py", line 107, in _call
    return call(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 1733, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
, via line: 167, in func: run, of file: C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py

